"""動画ビルダー

PPTXと音声ファイルからMP4動画を生成する。
各スライドをPNG画像にレンダリングし、対応する音声の実尺に合わせて
ffmpegで動画クリップを作成、最終的に1本のMP4に結合する。

依存ツール:
  - LibreOffice (PPTX → PNG レンダリング)
  - ffmpeg (動画合成・結合)
  - pdftoppm (poppler-utils, PDF→PNG変換。なければffmpegで代替)
"""

from __future__ import annotations

import json
import shutil
import subprocess
import warnings
from dataclasses import dataclass
from pathlib import Path

from pydub import AudioSegment


@dataclass(frozen=True)
class SlideClip:
    """スライドごとの動画クリップ情報。"""

    slide_index: int
    image_path: Path
    audio_path: Path | None
    duration: float  # 秒


_DEFAULT_SILENT_DURATION = 3.0  # 音声なしスライドのデフォルト秒数
_DEFAULT_AUDIO_PADDING = 1.5  # 音声ありスライドの前後パディング（秒）
_DURATION_TOLERANCE = 2.0  # バリデーション時のデュレーション許容誤差（秒）

# ffmpeg で奇数ピクセルを偶数化するフィルター
# libx264 (yuv420p) は幅・高さともに偶数でないとエンコードエラーになる
_PAD_EVEN_FILTER = "pad=ceil(iw/2)*2:ceil(ih/2)*2"


def get_audio_duration(audio_path: Path) -> float:
    """音声ファイルの実尺（秒）を取得する。

    Args:
        audio_path: MP3/WAV音声ファイルパス

    Returns:
        音声の長さ（秒）

    Raises:
        FileNotFoundError: ファイルが存在しない場合
    """
    seg = AudioSegment.from_file(str(audio_path))
    return seg.duration_seconds


def render_slides(pptx_path: Path, out_dir: Path) -> list[Path]:
    """LibreOfficeでPPTXの各スライドをPNG画像に変換する。

    PPTX→PDF→PNG の2段階で変換する。
    LibreOfficeの直接PNG変換は1枚目しか出力しないため。

    Note:
        snap版LibreOfficeはサンドボックス制限があるため、
        out_dir は $HOME 配下を推奨。/tmp 等は書き込み失敗する場合がある。

    Args:
        pptx_path: 入力PPTXファイルパス
        out_dir: PNG画像出力ディレクトリ

    Returns:
        スライド順にソートされたPNGファイルパスのリスト

    Raises:
        FileNotFoundError: LibreOfficeが見つからない場合
        RuntimeError: 変換が失敗した場合
    """
    lo = shutil.which("libreoffice")
    if lo is None:
        raise FileNotFoundError(
            "LibreOffice not found. Install with: "
            "apt install libreoffice / brew install libreoffice"
        )

    out_dir.mkdir(parents=True, exist_ok=True)

    # Step 1: PPTX → PDF
    pdf_dir = out_dir / "_pdf_tmp"
    pdf_dir.mkdir(parents=True, exist_ok=True)

    result = subprocess.run(
        [
            lo,
            "--headless",
            "--convert-to",
            "pdf",
            "--outdir",
            str(pdf_dir),
            str(pptx_path.resolve()),
        ],
        capture_output=True,
        text=True,
        timeout=120,
    )

    if result.returncode != 0:
        raise RuntimeError(f"PPTX→PDF conversion failed: {result.stderr}")

    pdf_files = list(pdf_dir.glob("*.pdf"))
    if not pdf_files:
        raise RuntimeError(
            "No PDF file generated by LibreOffice. "
            "If using snap, ensure out_dir is under $HOME."
        )

    pdf_path = pdf_files[0]

    # Step 2: PDF → PNG
    pdftoppm = shutil.which("pdftoppm")
    if pdftoppm:
        result = subprocess.run(
            [
                pdftoppm,
                "-png",
                "-r",
                "150",
                str(pdf_path),
                str(out_dir / "slide"),
            ],
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.returncode != 0:
            raise RuntimeError(f"pdftoppm failed: {result.stderr}")
    else:
        # ffmpeg fallback
        result = subprocess.run(
            [
                "ffmpeg",
                "-y",
                "-i",
                str(pdf_path),
                str(out_dir / "slide-%03d.png"),
            ],
            capture_output=True,
            text=True,
            timeout=120,
        )
        if result.returncode != 0:
            raise RuntimeError(f"ffmpeg PDF→PNG failed: {result.stderr}")

    # PDF一時ファイルのクリーンアップ
    shutil.rmtree(pdf_dir)

    pngs = sorted(out_dir.glob("*.png"))
    if not pngs:
        raise RuntimeError("No PNG files generated from PDF")

    return pngs


_DEFAULT_AUDIO_SAMPLE_RATE = 24000  # edge-tts のデフォルト出力サンプルレート


def _detect_sample_rate(clips: list[SlideClip]) -> int:
    """クリップリストから最初の音声ファイルのサンプルレートを検出する。

    音声ファイルがない場合はデフォルト値を返す。
    """
    for clip in clips:
        if clip.audio_path and clip.audio_path.exists():
            try:
                seg = AudioSegment.from_file(str(clip.audio_path))
                return seg.frame_rate
            except Exception:
                continue
    return _DEFAULT_AUDIO_SAMPLE_RATE


def build_clips(
    clips: list[SlideClip],
    out_dir: Path,
    fps: int = 30,
    audio_padding: float = _DEFAULT_AUDIO_PADDING,
) -> list[Path]:
    """ffmpegでスライドごとの動画クリップを生成する。

    音声ありクリップには audio_padding 分の無音パディングが末尾に付加される。
    これによりスライド切り替え時に「間（ま）」が生まれ、聞きやすくなる。

    Args:
        clips: スライドクリップ情報のリスト
        out_dir: クリップ出力ディレクトリ
        fps: フレームレート（デフォルト30）
        audio_padding: 音声ありスライドの末尾パディング（秒）

    Returns:
        生成されたクリップファイルパスのリスト
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    clip_paths: list[Path] = []

    # サイレント音声のサンプルレートを実際の音声に合わせる
    sample_rate = _detect_sample_rate(clips)

    for clip in clips:
        clip_path = out_dir / f"clip_{clip.slide_index:03d}.mp4"

        has_audio = clip.audio_path and clip.audio_path.exists()

        # 音声ありクリップにはパディングを追加
        total_duration = clip.duration + audio_padding if has_audio else clip.duration

        cmd = [
            "ffmpeg",
            "-y",
            "-loop",
            "1",
            "-framerate",
            str(fps),
            "-t",
            f"{total_duration:.3f}",
            "-i",
            str(clip.image_path),
        ]

        if has_audio:
            cmd.extend(["-i", str(clip.audio_path)])
            # apad: 音声末尾をゼロパディングで延長し、画像と同じ長さにする
            # -shortest: 画像（total_duration）に合わせて切り詰める
            audio_filter = f"apad=whole_dur={total_duration}"
            cmd.extend(["-af", audio_filter])
        else:
            # サイレント音声を生成（concat時のストリーム不一致を防ぐ）
            # サンプルレートは実際の音声ファイルと統一する
            cmd.extend([
                "-f",
                "lavfi",
                "-t",
                f"{total_duration:.3f}",
                "-i",
                f"anullsrc=r={sample_rate}:cl=stereo",
            ])

        cmd.extend([
            "-c:v",
            "libx264",
            "-tune",
            "stillimage",
            "-c:a",
            "aac",
            "-b:a",
            "192k",
            "-vf",
            _PAD_EVEN_FILTER,
            "-pix_fmt",
            "yuv420p",
            "-shortest",
        ])

        cmd.append(str(clip_path))

        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=120,
        )

        if result.returncode != 0:
            warnings.warn(
                f"ffmpeg clip failed for slide {clip.slide_index}: "
                f"{result.stderr[-300:]}",
                RuntimeWarning,
                stacklevel=2,
            )
            continue

        clip_paths.append(clip_path)

    return clip_paths


def concat_clips(clip_paths: list[Path], out_path: Path) -> Path:
    """ffmpegのconcat demuxerでクリップを1本のMP4に結合する。

    Args:
        clip_paths: 結合するクリップファイルパスのリスト
        out_path: 出力MP4ファイルパス

    Returns:
        出力MP4ファイルパス

    Raises:
        ValueError: clip_pathsが空の場合
        RuntimeError: ffmpegの結合が失敗した場合
    """
    if not clip_paths:
        raise ValueError("No clips to concatenate")

    out_path.parent.mkdir(parents=True, exist_ok=True)

    filelist = out_path.parent / "_filelist.txt"
    with open(filelist, "w") as f:
        for p in clip_paths:
            f.write(f"file '{p.resolve()}'\n")

    try:
        result = subprocess.run(
            [
                "ffmpeg",
                "-y",
                "-f",
                "concat",
                "-safe",
                "0",
                "-i",
                str(filelist),
                "-c",
                "copy",
                str(out_path),
            ],
            capture_output=True,
            text=True,
            timeout=300,
        )
    finally:
        filelist.unlink(missing_ok=True)

    if result.returncode != 0:
        raise RuntimeError(f"ffmpeg concat failed: {result.stderr}")

    return out_path


@dataclass(frozen=True)
class BuildResult:
    """動画ビルド結果。"""

    video_path: Path
    expected_duration: float  # 全クリップの合計デュレーション（秒）
    slide_count: int
    audio_count: int  # 音声ありスライド数


def build_video(
    pptx_path: Path,
    audio_dir: Path,
    out_path: Path,
    *,
    silent_duration: float = _DEFAULT_SILENT_DURATION,
    audio_padding: float = _DEFAULT_AUDIO_PADDING,
    fps: int = 30,
) -> BuildResult:
    """PPTXと音声ファイルからMP4動画を生成する。

    Args:
        pptx_path: 入力PPTXファイルパス
        audio_dir: 音声ファイルディレクトリ（slide_NNN.mp3形式）
        out_path: 出力MP4ファイルパス
        silent_duration: 音声なしスライドのデフォルト秒数
        audio_padding: 音声ありスライドの末尾パディング（秒）
        fps: フレームレート

    Returns:
        BuildResult（動画パス、期待デュレーション等）
    """
    work_dir = out_path.parent / "_video_work"
    slides_dir = work_dir / "slides"
    clips_dir = work_dir / "clips"

    try:
        # Step 1: PPTX → PNG
        slide_images = render_slides(pptx_path, slides_dir)

        # Step 2: SlideClip 情報を構築
        clips: list[SlideClip] = []
        for i, img in enumerate(slide_images):
            audio_path = audio_dir / f"slide_{i:03d}.mp3"
            if audio_path.exists():
                duration = get_audio_duration(audio_path)
                clips.append(SlideClip(i, img, audio_path, duration))
            else:
                clips.append(SlideClip(i, img, None, silent_duration))

        # Step 3: クリップ生成
        clip_paths = build_clips(clips, clips_dir, fps=fps, audio_padding=audio_padding)

        # Step 4: 結合
        concat_clips(clip_paths, out_path)

        # expected_duration は成功したクリップのみから計算
        # （build_clips が失敗スライドをスキップするため）
        # 音声ありクリップには audio_padding が加算される
        success_indices = {
            int(p.stem.split("_")[1]) for p in clip_paths
        }
        successful_clips = [
            c for c in clips if c.slide_index in success_indices
        ]
        expected_duration = sum(
            c.duration + (audio_padding if c.audio_path is not None else 0)
            for c in successful_clips
        )
        audio_count = sum(
            1 for c in successful_clips if c.audio_path is not None
        )

        return BuildResult(
            video_path=out_path,
            expected_duration=expected_duration,
            slide_count=len(successful_clips),
            audio_count=audio_count,
        )

    finally:
        if work_dir.exists():
            shutil.rmtree(work_dir)


# ---------------------------------------------------------------------------
# MP4 バリデーション
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class VideoInfo:
    """ffprobeで取得した動画情報。"""

    duration: float  # 秒
    width: int
    height: int
    video_codec: str
    audio_codec: str | None  # 音声なしの場合None
    audio_sample_rate: int | None
    file_size: int  # バイト
    nb_streams: int


def probe_video(video_path: Path) -> VideoInfo:
    """ffprobeでMP4の情報を取得する。

    Args:
        video_path: MP4ファイルパス

    Returns:
        VideoInfo

    Raises:
        FileNotFoundError: ファイルまたはffprobeが見つからない場合
        RuntimeError: ffprobeが失敗した場合
    """
    if not video_path.exists():
        raise FileNotFoundError(f"Video file not found: {video_path}")

    ffprobe = shutil.which("ffprobe")
    if ffprobe is None:
        raise FileNotFoundError("ffprobe not found (install ffmpeg)")

    result = subprocess.run(
        [
            ffprobe,
            "-v",
            "quiet",
            "-print_format",
            "json",
            "-show_format",
            "-show_streams",
            str(video_path),
        ],
        capture_output=True,
        text=True,
        timeout=30,
    )

    if result.returncode != 0:
        raise RuntimeError(f"ffprobe failed: {result.stderr}")

    data = json.loads(result.stdout)
    fmt = data["format"]
    streams = data["streams"]

    video_stream = None
    audio_stream = None
    for s in streams:
        if s["codec_type"] == "video" and video_stream is None:
            video_stream = s
        elif s["codec_type"] == "audio" and audio_stream is None:
            audio_stream = s

    if video_stream is None:
        raise RuntimeError("No video stream found in file")

    return VideoInfo(
        duration=float(fmt["duration"]),
        width=int(video_stream["width"]),
        height=int(video_stream["height"]),
        video_codec=video_stream["codec_name"],
        audio_codec=(
            audio_stream["codec_name"] if audio_stream else None
        ),
        audio_sample_rate=(
            int(audio_stream["sample_rate"]) if audio_stream else None
        ),
        file_size=int(fmt["size"]),
        nb_streams=int(fmt["nb_streams"]),
    )


def validate_video(
    video_path: Path,
    *,
    expected_duration: float | None = None,
    duration_tolerance: float = _DURATION_TOLERANCE,
) -> list[str]:
    """生成されたMP4動画をバリデーションする。

    チェック項目:
    1. ファイルが存在し、サイズ > 0
    2. ffprobeで読み取れる（破損していない）
    3. video streamが存在する（H.264）
    4. 解像度が偶数（libx264互換）
    5. 期待デュレーションとの乖離チェック（指定時）

    Args:
        video_path: MP4ファイルパス
        expected_duration: 期待されるデュレーション（秒）。Noneならスキップ
        duration_tolerance: デュレーション許容誤差（秒）

    Returns:
        エラーメッセージのリスト（空なら合格）
    """
    errors: list[str] = []

    # 1. ファイル存在・サイズ
    if not video_path.exists():
        return [f"File not found: {video_path}"]

    if video_path.stat().st_size == 0:
        return [f"File is empty: {video_path}"]

    # 2. ffprobe 読み取り
    try:
        info = probe_video(video_path)
    except (RuntimeError, FileNotFoundError, json.JSONDecodeError, KeyError) as e:
        return [f"Cannot read video: {e}"]

    # 3. コーデック
    if info.video_codec != "h264":
        errors.append(
            f"Unexpected video codec: {info.video_codec} (expected h264)"
        )

    if info.audio_codec is not None and info.audio_codec != "aac":
        errors.append(
            f"Unexpected audio codec: {info.audio_codec} (expected aac)"
        )

    # 4. 偶数解像度
    if info.width % 2 != 0:
        errors.append(f"Odd width: {info.width}")

    if info.height % 2 != 0:
        errors.append(f"Odd height: {info.height}")

    # 5. デュレーション
    if info.duration <= 0:
        errors.append(f"Invalid duration: {info.duration}")

    if expected_duration is not None:
        diff = abs(info.duration - expected_duration)
        if diff > duration_tolerance:
            errors.append(
                f"Duration mismatch: {info.duration:.1f}s "
                f"(expected {expected_duration:.1f}s "
                f"+/- {duration_tolerance:.1f}s)"
            )

    return errors
